version: '3.8'

services:
  store-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - SANIC_ENV=development
