version: '3.8'

services:
  store-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: store-backend:latest
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - SANIC_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite+aiosqlite:///store.db
